version: '3.7'
services :
    nginxserver:
        build:
            context: ./nginx
            dockerfile : Dockerfile-nginx
        ports : 
            - 8080:80
        image : 'nginx:latest'
        volumes:
             - ./content/:/nginx
             - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
             #- ./template/:/nginx
        links:
        - php
    php:
       # build:
       #     context : .
        #    dockerfile: Dockerfile-php
        image: 'php:7-fpm'
        volumes:
            - ./content:/nginx
           # - ./template:/nginx
    
  #  jenkins:
 #       build:
  #          context: ./jenkins
 #           dockerfile: Dockerfile-jenkins
 #       ports: 
 #           - 5000:5000
  #      image: 'jenkins/jenkins:lts'